## Credits: iNeuron.ai

## indexing and slicing of matrices

In [0]:
import numpy as np
from numpy.random import randint as ri 

In [2]:
arr=np.arange(0,11)
print('Array:',arr)

## printing element at the 7th index

print('\nElement at 7th index: ',arr[7])
print('\nElement at 3rd to 5th index: ',arr[3:5])
print('\nElement at 3rd and 5th index: ',arr[3:6:2])
print('\nElement upto 7th index: ',arr[:8])

## indexing backwards

print('\nElement till 1st index in reverse order: ',arr[::-3])

Array: [ 0  1  2  3  4  5  6  7  8  9 10]

Element at 7th index:  7

Element at 3rd to 5th index:  [3 4]

Element at 3rd and 5th index:  [3 5]

Element upto 7th index:  [0 1 2 3 4 5 6 7]

Element till 1st index in reverse order:  [10  7  4  1]


create a random matrix of integer with a dimension of (3,5)

In [3]:
int_mat=ri(0,100,15).reshape(3,5)
print(int_mat)

## printing intersection of rows and columns or in simple wprds slicing
print('\nprinting intersection  of rows 1 to 4 and col 3 to 5:\n','-'*60)
print(int_mat[1:4,3:5])
print('\nprinting by jumping columns\n','-'*60)
print(int_mat[1:4,0:5:2])
print('\nprinting by jumping rows and columns\n','-'*60)
print(int_mat[0:2:2,0:5:2])
print('\nprinting specific element(1,4)\n','-'*60)
print(int_mat[1][4])
print('\nchoosing multiple element((0,2) and (2,4)) to print\n','-'*60)
print(int_mat[[0,2],[2,4]])
# since here we dont have 3rd,4th row so it will start  from 1 and to max 2 and same for columns.

[[54 39 66 71 47]
 [ 7 74  9 83 90]
 [29 89 47 66  3]]

printing intersection  of rows 1 to 4 and col 3 to 5:
 ------------------------------------------------------------
[[83 90]
 [66  3]]

printing by jumping columns
 ------------------------------------------------------------
[[ 7  9 90]
 [29 47  3]]

printing by jumping rows and columns
 ------------------------------------------------------------
[[54 66 47]]

printing specific element(1,4)
 ------------------------------------------------------------
90

choosing multiple element((0,2) and (2,4)) to print
 ------------------------------------------------------------
[66  3]


Matrix or arrays are mutable

In [4]:
mut_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
mu_arr1=mut_arr[0:2,1:3]
print(mu_arr1)

## Now changing the value of the element (1,1)

mu_arr1[1][1]=100
print('\nMutated matrix\n','-'*60)
print(mu_arr1)

[[2 3]
 [5 6]]

Mutated matrix
 ------------------------------------------------------------
[[  2   3]
 [  5 100]]


fetching all the data based on some operator

In [5]:
## fetch all the data which is greater than 50

print(int_mat>50)
print('\n','-'*60)
print(int_mat[(int_mat>50)&(int_mat<70)])

[[ True False  True  True False]
 [False  True False  True  True]
 [False  True False  True False]]

 ------------------------------------------------------------
[54 66 66]


## Multiplication of two matrices

*   Element wise
*   Matrix multiplication



In [6]:
## element wise


mat1=ri(1,10,9).reshape(3,3)
mat2=ri(1,10,9).reshape(3,3)
print('\n matrix 1:\n','-'*60,'\n',mat1)
print('\n matrix 2:\n','-'*60,'\n',mat2)
mult_ele_wise=mat1*mat2
print('\nElement wise matrix multiplication\n','-'*60,'\n',mult_ele_wise)

## Matrix multiplication
mul_mat=mat1@mat2 ## yes! we use @ for regular matrix multiplication
print('\nmatrix multiplication\n','-'*60,'\n',mul_mat)
print('\n-------------------------------------------------------------\n',mat1/0) ## this will not give error



 matrix 1:
 ------------------------------------------------------------ 
 [[5 2 4]
 [7 2 9]
 [2 9 6]]

 matrix 2:
 ------------------------------------------------------------ 
 [[6 7 6]
 [1 4 9]
 [8 2 8]]

Element wise matrix multiplication
 ------------------------------------------------------------ 
 [[30 14 24]
 [ 7  8 81]
 [16 18 48]]

matrix multiplication
 ------------------------------------------------------------ 
 [[ 64  51  80]
 [116  75 132]
 [ 69  62 141]]

-------------------------------------------------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in true_divide
  del sys.path[0]


## **Array** **Math**

In [17]:
print(mat1)
print('\n',mat2)

## taking sq. root of the elements
print('\nsq. root of the elements\n','-'*60)
print(np.sqrt(mat1))

## taking exponential of the elements
print('\nexponential of the elements\n','-'*60)
print(np.exp(mat1))

## taking logarithmic of the elements
print('\nlogarithmic of the elements\n','-'*60)
print(np.log10(mat1))

## taking remainder of the element wise devision of all the elements
print('\nremainder of the element wise devision of all the elements\n','-'*80)
print(np.fmod(mat1,mat2))


[[5 2 4]
 [7 2 9]
 [2 9 6]]

 [[6 7 6]
 [1 4 9]
 [8 2 8]]

sq. root of the elements
 ------------------------------------------------------------
[[2.23606798 1.41421356 2.        ]
 [2.64575131 1.41421356 3.        ]
 [1.41421356 3.         2.44948974]]

exponential of the elements
 ------------------------------------------------------------
[[1.48413159e+02 7.38905610e+00 5.45981500e+01]
 [1.09663316e+03 7.38905610e+00 8.10308393e+03]
 [7.38905610e+00 8.10308393e+03 4.03428793e+02]]

logarithmic of the elements
 ------------------------------------------------------------
[[0.69897    0.30103    0.60205999]
 [0.84509804 0.30103    0.95424251]
 [0.30103    0.95424251 0.77815125]]

remainder of the element wise devision of all the elements
 --------------------------------------------------------------------------------
[[5 2 4]
 [0 2 0]
 [2 1 6]]
