# Credits: iNeuron.ai

In [0]:
import numpy as np
arr=np.array(['sdf',3,6.0])
print(arr)
type(arr)  ## this is ndarray which means n dimensionla array data type.

## UPCASTING

#Note: In the above arr, while cretaing it I passed different data type str, int and float 
#  but while printing I am only getting str elements. This is called UPCASTING

# Numpy bydefault upcasts all the elements to the largest element in th list passed
# for the above case larget memory consuming element was 'sdf' which is a string.

['sdf' '3' '6.0']


numpy.ndarray

In [0]:
## n-dimensions
# the dimensions of an array can be recognize by the number of square brackets it has.

#for example;

print(np.array([[1,2],[3,4]]))  #[[1 2]
                                # [3 4]]  this is the output  we got, hence this is 
                                # a 2-d array.

# converting into n- dimensions

print(np.array([1,2,3],ndmin=3)) # [[[1 2 3]]] here we have 3  sq brackets.



[[1 2]
 [3 4]]
[[[1 2 3]]]


# Data type changing of the elements in the array

In [0]:
print(np.array([4,5,6],dtype=complex)) ## This how each element of the given array can be changed into from int to complex.


# Lets understand what happens when we pass a tuple instead  of list to create an array..

arr1=np.array([(1,2),(4,5)],dtype=[('a','<i2'),('b','<i4')])
# So here in tuple a is represnting the first element of first tuple and b representing first element of second tuple.
# i2 and i4 vice versa.

# checking datatypes of each element
print(type(arr1[0][0])) # a=<class 'numpy.int16'>
print(type(arr1[0][1])) # i2=<class 'numpy.int32'>
print(type(arr1[1][0])) # b=<class 'numpy.int16'>
print(type(arr1[1][1])) # i4=<class 'numpy.int32'>


## Creatting an array from sub-classes

print(np.mat(np.array([[1,2],[6,7]])))
print(np.mat('1 2;"asfdf" 4'))


[4.+0.j 5.+0.j 6.+0.j]
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int16'>
<class 'numpy.int32'>
[[1 2]
 [6 7]]
[['1' '2']
 ['asfdf' '4']]


# np.asarray()

this is particularly used to compare two matrices if they are same or not

In [0]:
a=np.array([1,2],dtype=np.float64)
np.asarray(a) is a ## This will give True as answer as a==a

np.array([1,2]) is a # this gives false as a!=[1,2] as [1,2] has integrs but a has float64 as datatypes
print((np.asanyarray('efefwe')))

efefwe


# Copy operations

--> Shallow copy

--> Deep copy


In [0]:
## Shallow copy
import numpy as np

x=np.array([1,2,3])
y=x ## this is shallow copy, both x and y are in the same memory so changing one with change the other.
y[0]=100
print(x) ## out:array([100,   2,   3]) so changing any value in y will change the value in x.



# Deep copy
# here z is stored in different memmory altogether so z and x are different can be accessed separately
z=np.copy(x)
z[0]=200
print(x)
print('\n',z)


## chacking each by asarray()

print(np.asarray(z) is x) ## False
print(np.asarray(y) is x) ## True
## here is operator comparing the address 
print(id(x))  #140249298487456
print(id(y))  #140249298487456
print(id(z))  #140249298488176
 

[100   2   3]
[100   2   3]

 [200   2   3]
False
True
140145842568368
140145842568368
140145842568128


## Matrix creation and operations

In [0]:
## creating zero vector or matrix

print('\nVector of zeroes\n','-'*50)
print(np.zeros(5))

print('\nMatrix of zeroes\n','-'*50)
print(np.zeros((3,4)))
## np.zeros(int or (tuple of int)): this method can only take int or tuple of int as argument
 


Vector of zeroes
 --------------------------------------------------
[0. 0. 0. 0. 0.]

Matrix of zeroes
 --------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


-->Broadcasting 

In [0]:
print([[1,2,3]]+np.ones((3,3)))
print(6+np.ones((2,5))) ## here the integer 6 is braodcasted into a  2*5 matrix.

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


-->Identity matrices

In [0]:
id_mat=np.eye(5) ## identity matrix always takes one integer value as argument 
print(id_mat)

print(id_mat.shape)


np.linspace(0,100,50,endpoint=True,dtype=int)
#endpoint=True make sure that the upper bound of the given range is included.

np.logspace(0,2,num=2,base=10,endpoint=True)
# what logspace does is that it raise the the base to the powers of given start and end point..
np.logspace(0,3,3,base=2,endpoint=True)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


array([1.        , 2.82842712, 8.        ])

-->passing negative argument in the reshape() method

In [0]:
check_mat=np.arange(20).reshape((-1,4))
## depending upon the number of element, here is 20, reshape will return 
  # the matrix of dimension such that x*y=given size. In the above matrix the shape of the matrix is 5*4
print(check_mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


# np.diag(matrix,k=value)


-->if  k=+ve 

   means we will get the diagonal element of matrix removing k rows from bottom of the matrix and removing k columns from left of the matrix.

--> if k= -ve
   
   removes k rows from top of the matrix and removes k columns from right of the matrix.

In simple words k is the k th diagonal of the matrix, where k=0  for main diagonal.      

In [0]:
print(np.diag(check_mat,k=1))

## doubt: what if the matrix is not square?
print('\n'*3)
diag_ele=np.diag(check_mat,k=-2)
print(diag_ele)

[ 1  6 11]




[ 8 13 18]


# np.diag(np.diag(x))

Applying np.diag() twice, it will return a matrix with diagonal element given by np.diag(x). Where x is the matrix passed.

In [0]:
diag_element=np.diag(check_mat)
print(diag_element)
print('\n'*3)
double_diag_mat=np.diag(np.diag(check_mat))
print(double_diag_mat)

[ 0  5 10 15]




[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


# np.diagflat()

this will unravel the flat input and cretae a matrix keeping the flat input as a k-th diagonal element

In [0]:
np.diagflat([1,2,3],k=-2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Cretaing triangular matrix



1.   np.tri(row,col,k)
2.   np.tril(row,col,k)

1.   np.triu(row,col,k)







In [0]:
## np.tri()
print(np.tri(4,4,k=0,dtype=int))

## np.tril()
print('\nLower triangular matrix\n','-'*50)
print(np.tril([[1,2,3],[4,5,6],[7,8,9]],k=0))

## np.triu()
print('\nUpper triangular matrix\n','-'*50)
print(np.triu([[1,2,3],[4,5,6],[7,8,9]],k=0))

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]

Lower triangular matrix
 --------------------------------------------------
[[1 0 0]
 [4 5 0]
 [7 8 9]]

Upper triangular matrix
 --------------------------------------------------
[[1 2 3]
 [0 5 6]
 [0 0 9]]


# Random number generation

-->function used: np.random.randn((size of array))

this gives random data in the uniform normal distribution manner in the given array size.

In [0]:
## np.random.randn()
print('\nGenerating number randomly\n','-'*50)
print(np.random.randn(4,5))

## np.random.randint()
print('\nGenerating integer number randomly\n','-'*50)
print(np.random.randint (4,10,(3,4)))
# randint requires start int and end int with total number needs to be generated ot size of array.

print('\nGenerating 20 integer number randomly in between 10 and 100\n','-'*60)
print(np.random.randint (10,100,20))


Generating number randomly
 --------------------------------------------------
[[-0.25491697  1.37240259  0.18389204  0.33136011 -0.57596184]
 [ 1.5934778   0.15436788 -0.26064733 -2.45741303  0.93682585]
 [-0.63092259  0.92196445 -0.36928867 -0.13830589  0.76784971]
 [-0.21834225  0.11635243  1.22107516 -0.48720215  0.23623887]]

Generating integer number randomly
 --------------------------------------------------
[[7 7 8 7]
 [9 9 9 5]
 [8 6 9 9]]

Generating 20 integer number randomly in between 10 and 100
 ------------------------------------------------------------
[79 57 14 75 89 35 50 55 21 26 33 53 11 33 65 97 15 43 40 89]


# Sorting

function:  np.sort()

this gives the datain the ascending order.

In [0]:
a=np.random.randn(4,5)
b=np.sort(a,axis=1)
print(b)
print('\n','-'*50)
c=np.random.randint(1,100,(4,5))
print(np.sort(c,axis=1))

[[-1.12708831 -0.6149178   0.70428681  1.09899245  2.08823878]
 [-2.07205768 -0.93953553 -0.56635656  0.09799771  1.77825337]
 [-0.9033993  -0.74678992 -0.3708642  -0.0995004   0.76198577]
 [-1.85593425 -0.70862787 -0.31026304  0.47629101  0.52065432]]

 --------------------------------------------------
[[ 5  8 44 73 91]
 [15 63 70 76 78]
 [ 1 40 47 58 82]
 [ 8 25 46 85 90]]


matrix.max(), matrix.min(), matrix.argmax()

In [0]:
 ## max(): this return the actual max value
x=np.random.randint(1,100,(4,5))
print('\nMatrix  x\n','-'*50)
print(x)
print('\nMax value in whole x\n','-'*50)
print(x.max())
print('\nMax value in x by row wise \n','-'*50)
print(x.max(axis=0))
print('\nMax value in x column wise\n','-'*50)
print(x.max(axis=1))

## argmax() this returns the location of maximium value
print('\nlocation Max value in x column wise\n','-'*50)
print(x.argmax(axis=1))
print('\nlocation Max value in x row wise\n','-'*50)
print(x.argmax(axis=0))


Matrix  x
 --------------------------------------------------
[[ 8 62 76 43 98]
 [33 73 39 86 29]
 [67 80  6 97 35]
 [ 6 15 31 56  6]]

Max value in whole x
 --------------------------------------------------
98

Max value in x by row wise 
 --------------------------------------------------
[67 80 76 97 98]

Max value in x column wise
 --------------------------------------------------
[98 86 97 56]

location Max value in x column wise
 --------------------------------------------------
[4 3 3 3]

location Max value in x row wise
 --------------------------------------------------
[2 2 0 2 0]
